name: Cucumber Java Selenium Workflow

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (dev or stage)'
        required: true
        default: ${{ secrets.ENVIRONMENT }}
      tags:
        description: 'Tags to run'
        required: true
        default: 'all'

jobs:
  run_tests:
    name: Run Cucumber Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build and run tests
        run: mvn clean install 
      
      - name: Run java class
        run: java -cptarget/classes org.example.App
  

