name: Cucumber Java Selenium Workflow

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (dev or stage)'
        required: true
        default: 'dev'
        options: ['dev','stage']
    

jobs:
  build:
    name: Run Cucumber Tests
    runs-on: ubuntu-latest

    steps:
      

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'

      - name: set up env
        run: |
       
           echo "ENV=${{ github.event.inputs.env}}" >>$env:GIT_ENV
         
       
      - name: Build and run tests
        run: mvn clean install 
      
      - name: Run java class
        run: java -cptarget/classes org.example.App
  

